services:
  redis:
    image: "redislabs/redismod"
    ports:
       - "6379:6379"
  app:
    build: .
    ports:
        - "8080:5000"
    volumes:
        - .:/code
    depends_on:
        - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379